### ISSUE TITLE
Using statements cannot find MAPIWrapper after adding 1.1.12 from Nuget

### ISSUE THREAD

**Issue by SimonKravis** [northwoodspd/MAPIWrapper#4]
After adding MAPIWrapper 1.1.12 via Nuget to a Windows Forms C# project in VS 2019 Community on Win 10, MAPIWrapper appears in the list of references, but if I try to add a "using MAPIWrapper;" statement I get a message "The type or namespace 'MAPIWrapper'  could not be  found. Are you missing a Using directive or an assembly reference>"

The test project downloaded from github contains a reference to MAPIWrapper and a "using MAPIWrapper;" statement without any error.

**Comment by SimonKravis** [comment]
Closing and re-opening the solution fixed the problem.

**Comment by SimonKravis** [comment]
Next problem is that if 32-bit Outlook is already running, message send fails with General Email Failure message

**Comment by jacob-ewald** [comment]
Is the issue you're seeing related to the 32-bit versus 64-bit difference, or is it that Outlook is already running? 
I don't experience any exceptions with it already running with my 64-bit version.
